services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: gogymrest
      POSTGRES_PASSWORD: gogymrest
      POSTGRES_DB: gogym
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - gogym_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiuser -d apidb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  gogym_network:
    driver: bridge